<?php

/**
 * Created by PhpStorm.
 * User: alex
 * Date: 17.12.16
 * Time: 13:18
 */
namespace Conversio\Conversation\Mail;

use Conversio\Mail\Container\AbstractContainer;
use Conversio\Mail\Mail;

class MailContainer extends AbstractContainer
{
    /**
     * @param Mail $mail
     */
    public function addMail(Mail $mail)
    {
        $this->store[] = $mail;
        usort($this->store, function (Mail $a, Mail $b) {
            return $a->getCreatedAt() > $b->getCreatedAt();
        });
    }

    /**
     * @param $id
     *
     * @return Mail|mixed|null
     */
    public function getById($id)
    {
        foreach ($this->asArray() as $mail) {
            if ($mail->getId() === $id) {
                return $mail;
            }
        }

        return null;
    }

    /**
     * @return Mail[]
     */
    public function asArray(): array
    {
        return parent::asArray(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Mail|null
     */
    public function first()
    {
        return !$this->isEmpty() ? array_values($this->store)[0] : null;
    }

    /**
     * @return Mail|null
     */
    public function last()
    {
        return !$this->isEmpty() ? array_reverse(array_values($this->store))[0] : null;
    }

}